
package com.example.imagerecognition

import android.graphics.Bitmap
import org.pytorch.IValue
import org.pytorch.Module
import org.pytorch.Tensor
import org.pytorch.torchvision.TensorImageUtils
import java.io.File

/**
 * Image Classification using ghost_resnet18_mobile
 * 
 * Generated by ResNet Optimization Research Framework
 */
class ImageClassifier(private val modelPath: String) {
    
    private var module: Module? = null
    
    private val classNames = listOf(
        "airplane", "automobile", "bird", "cat", "deer", "dog", "frog", "horse", "ship", "truck"
    )
    
    init {
        module = Module.load(modelPath)
    }
    
    /**
     * Classify an image
     * @param bitmap Input image as Bitmap
     * @return Pair of (class name, confidence score)
     */
    fun classify(bitmap: Bitmap): Pair<String, Float> {
        // Preprocess image
        val inputTensor = TensorImageUtils.bitmapToFloat32Tensor(
            bitmap,
            floatArrayOf(0.485f, 0.456f, 0.406f),  // mean
            floatArrayOf(0.229f, 0.224f, 0.225f)   // std
        )
        
        // Run inference
        val outputTensor = module?.forward(IValue.from(inputTensor))?.toTensor()
        
        // Get scores
        val scores = outputTensor?.dataAsFloatArray ?: return Pair("Unknown", 0f)
        
        // Softmax
        val expScores = scores.map { Math.exp(it.toDouble()).toFloat() }
        val sumExp = expScores.sum()
        val probabilities = expScores.map { it / sumExp }
        
        // Find max
        val maxIdx = probabilities.indices.maxByOrNull { probabilities[it] } ?: 0
        
        return Pair(classNames[maxIdx], probabilities[maxIdx])
    }
    
    /**
     * Get top-k predictions
     */
    fun classifyTopK(bitmap: Bitmap, k: Int = 5): List<Pair<String, Float>> {
        val inputTensor = TensorImageUtils.bitmapToFloat32Tensor(
            bitmap,
            floatArrayOf(0.485f, 0.456f, 0.406f),
            floatArrayOf(0.229f, 0.224f, 0.225f)
        )
        
        val outputTensor = module?.forward(IValue.from(inputTensor))?.toTensor()
        val scores = outputTensor?.dataAsFloatArray ?: return emptyList()
        
        // Softmax
        val expScores = scores.map { Math.exp(it.toDouble()).toFloat() }
        val sumExp = expScores.sum()
        val probabilities = expScores.map { it / sumExp }
        
        // Top-k
        return probabilities.indices
            .sortedByDescending { probabilities[it] }
            .take(k)
            .map { Pair(classNames[it], probabilities[it]) }
    }
    
    fun release() {
        module?.destroy()
        module = null
    }
}

// Usage example in Activity:
// val classifier = ImageClassifier(assetFilePath(this, "ghost_resnet18_mobile.ptl"))
// val (className, confidence) = classifier.classify(bitmap)
